name: dailydone
description: Daily Done, track your daily todos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # Local storage for preferences
  shared_preferences: ^2.2.2

  # Date formatting
  intl: ^0.18.1

  # Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  app_settings: ^5.1.1

  # UI enhancements
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true